name: Test SWEMniCS

on:
  # Trigger tests on push
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # '*' is a special character in YAML, so string must be quoted
    - cron: "0 8 * * *"
jobs:
  examples:
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/dolfinx:stable

    # strategy:
    #   matrix:
    #     build_mode: []
    env:
      HDF5_MPI: "ON"
      HDF5_DIR: "/usr/local/"
      DEB_PYTHON_INSTALL_LAYOUT: deb_system
    steps:
      - uses: actions/checkout@v4

      - name: upgrade pip
        run: python3 -m pip install  --upgrade setuptools pip

      #   - name: Check formatting
      #     run: |
      #       python3 -m pip install  ruff
      #       ruff check
      #       ruff format

      #   - name: Check typing
      #     run: |
      #       python3 -m pip install  mypy
      #       cd python
      #       python3 -m mypy . --exclude=build

      - name: Install h5py
        run: |
          python3 -m pip install --no-build-isolation  --no-cache-dir --no-binary=h5py h5py

      - name: Install package
        run: |
          python3 -m pip install --no-build-isolation --no-cache-dir -e .[examples]

      - name: Run smooth solution example
        working-directory: examples
        run: |
          python3 smooth_analytic_solution.py cg
          python3 smooth_analytic_solution.py dg
          python3 smooth_analytic_solution.py supg
          python3 smooth_analytic_solution.py dgcg

      - name: Run dam-break example
        working-directory: examples
        run: |
          python3 dam_break.py cg
          python3 dam_break.py dg
          python3 dam_break.py supg
          python3 dam_break.py dgcg

      - name: Run gulf
        working-directory: examples
        run: |
          python3 gulf.py --solver dg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ike_dg
          path: ./examples/ike_dg_quadratic_dt3600_nprocs1_tide_only
